### ISSUE TITLE
Use of Undeclared type 'Tasks'

### ISSUE THREAD

**Issue by lenichols** [rshankras/TaskManager#1]
I am using XCode 6.3 and swift 1.2 but running your code presents an error "Use of undeclared type 'Tasks'... it is being declared but coming back as undeclared... 

let task:Tasks = fetchedResultController.objectAtIndexPath(indexPath!) as! Tasks

What can be the issue? I see many having the same problem.

**Comment by rshankras** [comment]
I am not sure about Xcode 6.4, please try upgrading to 6.4. I have checked this again in Xcode 6.4 and it works.

Also make sure you have generated CoreData class (Tasks.Swift).
